config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  resources :registrations, only: %i[index create] do
    collection do
      get :cred_login
      post :user_callback
      post :cred_callback
    end
  end

  resources :notes, except: :index

  resources :dashboard, only: %i[index destroy] do
    collection do
      get :credentials
      get :cred_options
      post :callback
    end
  end

  delete 'signout', to: 'dashboard#signout'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/credential.rb
# frozen_string_literal: true

class Credential < ApplicationRecord
  belongs_to :user
end

app/models/note.rb
# frozen_string_literal: true

class Note < ApplicationRecord
  belongs_to :user

  validates :title, presence: true

  def word_count
    content.split(' ').length
  end

  def first_words
    return 'No Content' if content.blank?

    line = content.split(/\s/)
    "#{line[0...8].join(' ')}..."
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_create :initialize_webauthn_id

  has_many :credentials, dependent: :destroy
  has_many :notes, dependent: :destroy

  validates :username, uniqueness: true

  def initialize_webauthn_id
    # user.update!(webauthn_id: WebAuthn.generate_user_id)
    self.webauthn_id = WebAuthn.generate_user_id
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_user

  def set_user
    @current_user = User.find_by(id: cookies.signed[:signin_token])

    redirect_to registrations_path if @current_user.blank?
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  layout 'dash'

  before_action :credential_check, only: :destroy
  before_action :signout_check, only: :signout

  def index; end

  def credentials
    @credentials = @current_user.credentials
  end

  def cred_options
    # Credential/PassKey options
    create_options = WebAuthn::Credential.options_for_create(
      user: {
        id: @current_user.webauthn_id,
        name: @current_user.username
      },
      exclude: @current_user.credentials.pluck(:external_id),
      authenticator_selection: {
        user_verification: 'preferred',
        authenticator_attachment: 'platform',
        require_resident_key: true
      }
    )

    # Store challenge for verification
    session[:challenge] = create_options.challenge

    respond_to do |format|
      format.json { render json: create_options }
    end
  end

  def callback
    webauthn_credential = WebAuthn::Credential.from_create(params)

    begin
      webauthn_credential.verify(session[:challenge], user_verification: true)

      credential = @current_user.credentials.build(
        external_id: Base64.strict_encode64(webauthn_credential.raw_id),
        nickname: "crdtl_#{Time.zone.now.strftime('%y')}",
        public_key: webauthn_credential.public_key,
        sign_count: webauthn_credential.sign_count
      )

      if credential.save
        render json: { status: 'ok' }, status: :ok
      else
        render json: "Couldn't register your PassKey", status: :unprocessable_entity
      end
    rescue WebAuthn::Error => e
      render json: "Verification failed: #{e.message}", status: :unprocessable_entity
    ensure
      session.delete :challenge
    end
  end

  def destroy
    @credential = Credential.find(params[:id])
    @credential.delete

    redirect_to credentials_dashboard_index_path
  end

  def signout
    cookies.delete :signin_token

    redirect_to registrations_path
  end

  private

  def credential_check
    return if @current_user.credentials.count > 1

    flash[:notice] = 'You need at least one passkey!'
    redirect_to credentials_dashboard_index_path
  end

  def signout_check
    return if @current_user.credentials.count >= 1

    flash[:notice] = 'You need at least one passkey!'
    redirect_to credentials_dashboard_index_path
  end
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

class NotesController < ApplicationController
  layout 'dash'

  before_action :set_note, only: %i[show edit update destroy]

  def show; end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to root_path
    else
      flash[:notice] = @note.errors.full_messages.uniq

      redirect_to new_note_path
    end
  end

  def edit; end

  def update
    if @note.update(note_params)
      redirect_to root_path
    else
      flash[:notice] = @note.errors.full_messages.uniq

      redirect_to edit_note_path(@note)
    end
  end

  def destroy
    @note.delete

    redirect_to root_path
  end

  private

  def note_params
    params.require(:note).permit(:title, :content, :user_id)
  end

  def set_note
    @note = Note.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  skip_before_action :set_user

  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user(@user)

      redirect_to dashboard_index_path
    else
      flash[:notice] = @user.errors.full_messages.uniq

      redirect_to registrations_path
    end
  end

  def cred_login; end

  def user_callback
    user = User.find_by(username: params[:user])

    return no_user_error unless user

    options = WebAuthn::Credential.options_for_get(
      allow: user.credentials.map(&:external_id)
    )

    # Store challenge somewhere for verification and user id for lookup if successful
    session[:authentication_challenge] = {
      challenge: options.challenge,
      user: user.id
    }

    render json: options
  end

  def cred_callback
    webauthn_credential = WebAuthn::Credential.from_get(params)

    user = User.find(session[:authentication_challenge]['user'])
    credential = user.credentials.find_by(external_id: Base64.strict_encode64(webauthn_credential.raw_id))

    begin
      webauthn_credential.verify(
        session[:authentication_challenge]['challenge'],
        public_key: credential.public_key,
        sign_count: credential.sign_count
      )

      credential.update!(sign_count: webauthn_credential.sign_count)

      login_user(user)
      logger.info "Logged in #{user.username}"

      render json: { status: 'ok' }, status: :ok
    rescue WebAuthn::Error => e
      render json: "Verification failed: #{e.message}", status: :unprocessable_entity
      logger.warn "Verification error: #{e.message}"
    ensure
      session.delete('authentication_challenge')
    end
  end

  private

  def login_user(user)
    cookies.signed[:signin_token] = user.id
  end

  def user_params
    params.require(:user).permit(:username)
  end

  def no_user_error
    logger.warn 'No user found for given username'
    render json: { error: 'No User found' }
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

module NotesHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true

module RegistrationsHelper
end

app/views/dashboard/credentials.html.erb
<div class="row">
  <h2>Your Passkeys</h2>
</div>

<% if flash.notice %>
  <div class="text-danger">
    <p><%= flash.notice %></p>
  </div>
<% end %>

<div id="errors-box"></div>

<table class="table w-75 mx-auto border" id="credential-table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Created At</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% if @credentials.length > 0 %>
      <% @credentials.each do |key| %>
        <%= render partial: 'shared/key_row', locals: {credential: key} %>
      <% end %>
    <% else %>
      <tr>
        <td colspan='3'>No Credentials!</td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="card mx-auto p-2 w-50">
    <div class="card-header">
      <h4 class="text-center">New Passkey</h4>
    </div>

    <div class="card-body d-flex justify-content-center">
      <button id="credential-btn" class="btn btn-primary mx-auto">Create</button>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="row">
  <h2 class="col-md-6">Your Notes</h2>
  <strong>You Have <%= @current_user.notes.length %></strong>
</div>

<div class="container-fluid d-flex flex-wrap justify-content-center">
  <% @current_user.notes.each do |note| %>
    <%= render partial: 'shared/note_card', locals: { note: } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebauthnNoteApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg border bg-body-tertiary">
      <div class="container-fluid">
        <h2><%= link_to 'MyNote', registrations_path, class: 'navbar-brand' %></h2>
      </div>
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/dash.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyNoteApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<div class="mx-auto my-5 w-75 border p-2">
  <div class="row mb-3">
    <h2 class="mb-2"><%= @note.new_record? ? 'New Note' : 'Edit Note' %><h2>
    <div class="bg-danger">
      <% if flash.notice %>
        <div class="text-white">
          <% flash.notice.each do |notice| %>
            <p><%= notice %></p>
          <% end %>
          </div>
      <% end %>
  </div>
  </div>

  <%= form_with model: @note, class: 'form p-2' do |f| %>
    <%= f.hidden_field :user_id, value: @current_user.id %>
    <div class="mb-3 row">
      <%= f.label :title, class: 'form-label' %>
      <%= f.text_field :title, placeholder: 'Name...', class: 'form-control' %>
    </div>
    <div class="mb-3 row">
      <%= f.label :content, class: 'form-label' %>
      <%= f.text_area :content, placeholder: 'Content...', size: "70x5", class: 'form-control' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/notes/edit.html.erb
<%= render partial: 'form' %>

app/views/notes/new.html.erb
<%= render partial: 'form' %>

app/views/notes/show.html.erb
<div class="row my-3">
  <h2><%= @note.title %></h2>
  <strong>Word Count: <%= @note.word_count %></strong>
  <%= link_to 'Edit', edit_note_path(@note), class: 'btn btn-warning btn-sm col-sm-1 m-1' %>
</div>

<div class="row mb-3">
  <strong>Content:</strong>
</div>

<div class="container">
  <%= @note.content %>
</div>

app/views/shared/_key_row.html.erb
<tr class="table-hover">
  <td><%= credential.nickname %></td>
  <td><%= credential.created_at.strftime('%d-%m-%Y') %></td>
  <td><%= link_to 'Delete', dashboard_path(credential.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger btn-sm' %></td>
</tr>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg border bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">MyNote</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Credentials', credentials_dashboard_index_path, class: 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Logout', signout_path, data: {turbo_method: :delete}, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <li class="disabled nav-item m-auto"><%= @current_user.username %></li>
      </ul>
      <%= link_to 'New Note', new_note_path, class: 'btn btn-success' %>
    </div>
  </div>
</nav>

app/views/shared/_note_card.html.erb
<div class="card m-1 p-3">
  <div class="row">
    <h3><%= link_to note.title, note %></h3>
  </div>
  <div class="card-body">
    <div class="row justify-content-center">
      <div class="col-sm-9">
        <%= note.first_words %>
      </div>
    </div>

    <div class="row p-1">
      <%= link_to 'Edit', edit_note_path(note), class: 'btn btn-warning btn-sm mx-auto card-link' %>
      <%= link_to "Delete", note_path(note), data: { turbo_method: "delete", turbo_confirm: "Are you sure?"}, class: 'btn btn-danger btn-sm card-link mx-auto' %>
    </div>
  </div>
</div>